research generating SVGs without converting text to paths
https://www.pivotaltracker.com/story/show/168929055

* trying a mirror URL for TeXLive installer
* hopefully this will be less unstable

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -6,36 +6,45 @@
 
 BUILD_DIR=$1
 CACHE_DIR=$2
-ENV_DIR=$3
 BIN_DIR=$(cd "$(dirname "$0")"; pwd) # absolute path
 CONF_DIR="$BIN_DIR/../conf"
-
-TEXLIVE_REPOSITORY="ftp://tug.org/historic/systems/texlive/2017/tlnet-final"
-if [ -f $ENV_DIR/TEXLIVE_REPOSITORY ]; then
-    TEXLIVE_REPOSITORY=$(cat $ENV_DIR/TEXLIVE_REPOSITORY)
-fi
-
-TEXLIVE_INSTALLER_URL="$TEXLIVE_REPOSITORY/install-tl-unx.tar.gz"
-
-TEXLIVE_HOME=$BUILD_DIR/.texlive
-TEXLIVE_CACHE=$CACHE_DIR/.texlive
-PATH=$TEXLIVE_HOME/bin/x86_64-linux:$PATH
-PROFILE_D=$BUILD_DIR/.profile.d/texlive.sh
-
-TEXMF_LOCAL=$TEXLIVE_HOME/texmf-local/tex/latex/local
-mkdir -p $TEXMF_LOCAL
 
 # Output helpers
 # shellcheck source=bin/utils
 source "$BIN_DIR/utils"
 
+MOST_CURRENT_REPOSITORY="http://mirror.ctan.org/systems/texlive/tlnet"
+ARCHIVED_REPOSITORY_MIRROR="ftp://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2017/tlnet-final"
+TEXLIVE_REPOSITORY=$ARCHIVED_REPOSITORY_MIRROR
+CUSTOM_REPOSITORY_FILE="texlive.repository"
+CUSTOM_REPOSITORY_PATH="$BUILD_DIR/$CUSTOM_REPOSITORY_FILE"
+
+# Optional: use custom path to texlive installer
+if [ -f $CUSTOM_REPOSITORY_PATH ]; then
+    TEXLIVE_REPOSITORY=$(cat $CUSTOM_REPOSITORY_PATH)
+    build-step "Using custom repository defined in config file ~/$CUSTOM_REPOSITORY_FILE: ~/$TEXLIVE_REPOSITORY"
+fi
+
+build-step "Installing TeXLive from $TEXLIVE_REPOSITORY"
+
+TEXLIVE_INSTALLER_URL="$TEXLIVE_REPOSITORY/install-tl-unx.tar.gz"
+
+TEXLIVE_HOME=$BUILD_DIR/.texlive
+TEXLIVE_CACHE=$CACHE_DIR/.texlive
+TEXMF_LOCAL=$TEXLIVE_HOME/texmf-local/tex/latex/local
+PATH=$TEXLIVE_HOME/bin/x86_64-linux:$PATH
+PROFILE_D=$BUILD_DIR/.profile.d/texlive.sh
+
 # Prepare the various paths
 mkdir -p "$TEXLIVE_HOME"
 mkdir -p "$TEXLIVE_CACHE"
+mkdir -p "$TEXMF_LOCAL"
 mkdir -p "$(dirname "$PROFILE_D")"
 
-build-step "BIN_DIR: $BIN_DIR"
 build-step "BUILD_DIR: $BUILD_DIR"
+build-step "CACHE_DIR: $CACHE_DIR"
+build-step "BIN_DIR: $BIN_DIR"
+build-step "CONF_DIR: $CONF_DIR"
 build-step "TEXLIVE_REPOSITORY: $TEXLIVE_REPOSITORY"
 build-step "TEXLIVE_INSTALLER_URL: $TEXLIVE_INSTALLER_URL"
 build-step "TEXLIVE_HOME: $TEXLIVE_HOME"
@@ -47,27 +56,23 @@ if [ "$(ls -A "$TEXLIVE_CACHE")" ]; then
     cp -R "$TEXLIVE_CACHE/"* "$TEXLIVE_HOME"
 fi
 
+if [ ! -f "$TEXLIVE_HOME/install-tl" ]; then
+    build-step "Downloading install-tl using $TEXLIVE_INSTALLER_URL..."
+    curl "$TEXLIVE_INSTALLER_URL" -L -s -o - | tar --strip-components=1 -xzf - -C "$TEXLIVE_HOME"
+fi
+
 if [ ! "$(which pdflatex)" ]; then
     build-step "Installing TeX Live..."
 
-    if [ ! -f "$TEXLIVE_HOME/install-tl" ]; then
-        build-step "Downloading install-tl from $TEXLIVE_INSTALLER_URL"
-        curl "$TEXLIVE_INSTALLER_URL" -L -s -o - | tar --strip-components=1 -xzf - -C "$TEXLIVE_HOME"
-        if [ ! -f "$(which $TEXLIVE_HOME/install-tl)" ]; then
-            build-warn "Unable to download TeX installer!"
-            exit 0
-        fi
-    fi
-
     PROF=$BIN_DIR/../conf/texlive.profile
     {
-        echo "TEXDIR $TEXLIVE_HOME";
-        echo "TEXMFCONFIG $TEXLIVE_HOME/var/texmf-config";
-        echo "TEXMFHOME $TEXLIVE_HOME/var/texmf";
-        echo "TEXMFLOCAL $TEXLIVE_HOME/texmf-local";
-        echo "TEXMFSYSCONFIG $TEXLIVE_HOME/texmf-config";
-        echo "TEXMFSYSVAR $TEXLIVE_HOME/texmf-var";
-        echo "TEXMFVAR $TEXLIVE_HOME/var/texmf-var";
+      echo "TEXDIR $TEXLIVE_HOME";
+      echo "TEXMFCONFIG $TEXLIVE_HOME/var/texmf-config";
+      echo "TEXMFHOME $TEXLIVE_HOME/var/texmf";
+      echo "TEXMFLOCAL $TEXLIVE_HOME/texmf-local";
+      echo "TEXMFSYSCONFIG $TEXLIVE_HOME/texmf-config";
+      echo "TEXMFSYSVAR $TEXLIVE_HOME/texmf-var";
+      echo "TEXMFVAR $TEXLIVE_HOME/var/texmf-var";
     } >> "$PROF"
 
     cd "$TEXLIVE_HOME"
@@ -75,39 +80,21 @@ if [ ! "$(which pdflatex)" ]; then
     ./install-tl --repository="$TEXLIVE_REPOSITORY" --profile="$PROF"
 fi
 
-# Check for an essential binary to make sure it's installed
-if [ ! "$(which latex)" ]; then
-    build-warn "TeX Live installation failed"
-    build-warn "TeX will be unavailable until this is addressed"
-    exit 0
+build-step "Updating TeX Live..."
+
+tlmgr option repository "$TEXLIVE_REPOSITORY"
+tlmgr update --self
+
+# install user-provided-packages
+if [ -f "$BUILD_DIR/texlive.packages" ]; then
+    build-step "Installing custom packages..."
+    # shellcheck disable=SC2046
+    tlmgr install $(cat "$BUILD_DIR/texlive.packages")
 fi
 
-if wget -q $TEXLIVE_REPOSITORY/README.md
-then
-  # the repository is responsive
-  build-step "Updating TeX Live..."
+build-step "Updating installed packages..."
+tlmgr update --all
 
-  tlmgr option repository "$TEXLIVE_REPOSITORY"
-
-  build-step "TeX Live repository set to $TEXLIVE_REPOSITORY"
-
-  tlmgr update --self
-
-  # install user-provided-packages
-  if [ -f "$BUILD_DIR/texlive.packages" ]; then
-      build-step "Installing custom packages..."
-      # shellcheck disable=SC2046
-      tlmgr install $(cat "$BUILD_DIR/texlive.packages")
-  fi
-
-  build-step "Updating installed packages..."
-  tlmgr update --all
-else
-  build-warn "Unable to access $TEXLIVE_REPOSITORY; falling back on cached installation"
-  exit 0
-fi
-
-build-step "TeX Live installation successful!"
 build-step "Cleaning up temporary files..."
 # Make sure the cache is empty
 rm -rf "${TEXLIVE_CACHE:?}/"*
@@ -115,6 +102,12 @@ rm -rf "${TEXLIVE_CACHE:?}/"*
 build-step "Caching..."
 # Store a copy of it in the cache so it doesn't have to be fetched again
 cp -R "$TEXLIVE_HOME/"* "$TEXLIVE_CACHE/"
+
+# Check for an essential binary to make sure it's installed
+if [ ! "$(which pdflatex)" ]; then
+    build-warn "TeX Live installation failed"
+    exit 1
+fi
 
 # Set up the environment for runtimes now that compilation has finished
 # shellcheck disable=SC2016
@@ -124,13 +117,13 @@ echo 'export PATH=$HOME/.texlive/bin/x86_64-linux:$PATH' > "$PROFILE_D"
 # EDC: install cam's Tikz files in the texmf hierarchy #
 ########################################################
 
-build-step "Adding custom sty and cls files to TeX path"
+build-step "Copying custom sty and cls files to TeX path from $CONF_DIR..."
 for file in $CONF_DIR/*.{sty,cls}; do
-    echo "Copying $file to $TEXMF_LOCAL"
+    build-step "Copying $file to $TEXMF_LOCAL"
     cp $file $TEXMF_LOCAL
 done
 
 build-step "Running texhash..."
 texhash
 
-build-step "Done adding sty files to TeX path!"
+build-step "TeX Live installation successful!"
